# Docker Compose file: Web app with PostgreSQL and Redis services, in reality we would pass all sensitive variables (if not all of them) from the environment to prevent sensitive data from being exposed on disk outside of OS user perm control


services:
  webapp:
    image: myapp/webapp:latest
    build:
      context: ./webapp
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/appdb
      - REDIS_URL=redis://redis:6379
    depends_on:
      - db
      - redis
    restart: always

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user_passed_as_env_var
      POSTGRES_PASSWORD: password_passed_as_env_var
      POSTGRES_DB: appdb_passed_as_env_var
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: always

volumes:
  db_data:
